collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4928315
  brandStrength: 1
  lightness: 0.2647555
  brandColors:
    - '#313131'
    - '#BFBFBF'
    - '#9F9F9F'
    - '#0F0F0F'
    - '#DFDFDF'
  rhythmicContrast: 1
typography_spectrum: 0
layout_spectrum: 0.9313023
name: Luis Mena Fotografía
