layout_spectrum: 0.2682198
color:
  saturation: 0.3462758
  brandStrength: 1
  lightness: 0.0822406
  rhythmicContrast: 0.8624607
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.0925926
name: Luis Mena Fotografía
